### ISSUE TITLE
Question regarding pytorch3d and pointclouds

### ISSUE THREAD

**Issue by ttsesm** [SamGalanakis/pytorch3dPointnet#1]
Hi @SamGalanakis,

I recently found your current test project where you are trying to use pytorch3d for implementing Pointnet. Thus, I would like to ask you a couple of questions if you know and possibly you are familiar with the pytorch3d `Pointclouds` class. 

I would like to use pytorch3d with the `Pointclouds` class for solving based on one of their inserted features. Something like that:

```
    verts = [torch.Tensor(p).to(device) for p in pcds]

    illum = [torch.Tensor(x).to(device) for x in lx]

    trg_point_clouds = Pointclouds(points=verts, features=illum)

    src_point_clouds = Pointclouds(points=verts)

    # We want to learn to estimate the source point cloud vertices energy
    # The shape of the estimated energy values is equal to the total number of vertices in trg_mesh
    _illum = torch.full(trg_point_clouds.features_packed().shape, 0.0, device=device, requires_grad=True)

    # The optimizer
    optimizer = torch.optim.SGD([_illum], lr=1.0, momentum=0.9)

    n_iter = 2000
    epoch = tqdm(range(n_iter))

    loss_f = torch.nn.L1Loss()
    losses = []

    for i in epoch:
        # Initialize optimizer
        optimizer.zero_grad()

        # Update of features
        src_point_clouds.features_packed = _illum

        # We compare the two sets of pointclouds by computing the L1 loss
        loss = loss_f(trg_point_clouds, src_point_clouds)

        # Print the losses
        epoch.set_description('total_loss = %.6f' % loss)

        # Save the losses for plotting
        losses.append(loss)

        # Optimization step
        loss.backward()
        optimizer.step()
```

where `pcds` are my point clouds (Nx3 points) and `lx` the corresponding gt features (it is just an array Nx1) for which I want to optimize. The above doesn't really work and I am trying to figure out how to modify it.

In case, thank you for your time.

**Comment by SamGalanakis** [comment]
Not very experienced with pytorch3d yet but might be able to help. Why are you manually setting  src_point_clouds.features_packed = _illum at each iteration? Would think passing it when initially creating src_point_clouds as you do for trg_point_clouds should be enough. What error are you getting? Or just no learning?

**Comment by ttsesm** [comment]
Hi Sam, thanks for the prompt response. So you mean something like that:

```
    illum = [torch.Tensor(x).to(device) for x in lx]
    trg_point_clouds = Pointclouds(points=verts, features=illum)
    test_illum = [torch.Tensor(x*0).to(device) for x in lx] # I set the predicted values to zero and then add it in the src_point_clouds below
    src_point_clouds = Pointclouds(points=verts, features=test_illum)
```

and then inside the optimization loop I just get the loss?

I am not sure though whether the `_illum = torch.full(trg_point_clouds.features_packed().shape, 0.0, device=device, requires_grad=True)` is correct/needed at all or not though.

I am passing the `src_point_clouds.features_packed = _illum` at each iteration because I was trying to follow the tutorial regarding the [deform mesh](https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh) where if you notice in the optimization loop they update the vertices each time:
```
    # Deform the mesh
    new_src_mesh = src_mesh.offset_verts(deform_verts)
```

If I do the above, it seems that I have two issues 1) my torch L1 loss cannot handle the `Pointclouds` objects since it gives me 

```
    if not (target.size() == input.size()):
AttributeError: 'Pointclouds' object has no attribute 'size'
```

and 2) I've tried to use the chamfer loss instead from pytorch3d just to experiment and while I do not get the above error it seems not be learning since it returns 0 in the loss.

**Comment by SamGalanakis** [comment]
In the example, the trainable parameters are deform_verts, he does new_src_mesh so that a new mesh can be made with the new deformations and resampled. In your case you seem to be learning _illum which is just a feature vector, not really changing the pointcloud in any way so you shouldn't need to keep setting it. Would be easy to check by running and seeing if the parameters update after the first backward pass. If you want to take L1 loss maybe try using mesh.points_packed to get the tensor although with how you are setting your meshes up now they seem to have the same points so it makes sense that loss would be 0. Maybe you want to define loss on the features?

**Comment by ttsesm** [comment]
Well  I am trying and want to learn on a feature vector instead of the whole point cloud (mesh in the example), that's one of the differences in my case scenario comparing with the pytorch3d example I've linked. Also in my case I do not have the `Meshes` class but rather the `Pointclouds` class that I want to use. So the 3d points it is fine to stay unchanged, since I am interested to learn the features vector as I said.

> Maybe you want to define loss on the features?

Yes I guess this is what I should be setting the loss to be. 

So based on what you are suggesting something like:
```
loss = loss_f(trg_point_clouds.features_packed(), src_point_clouds.features_packed())
```
should work. 

I'll give it a try and update

**Comment by ttsesm** [comment]
Hi Sam,

Ok, modifying the code to the one below:
```
    verts = [torch.Tensor(p).to(device) for p in pcds]
    illum = [torch.Tensor(x).to(device) for x in lx]
    trg_point_clouds = Pointclouds(points=verts, features=illum)

    _illum = [torch.Tensor(x*0).to(device) for x in lx]
    src_point_clouds = Pointclouds(points=verts, features=_illum)

    # We will learn to estimate the source point cloud vertices energy
    # The shape of the estimated energy values is equal to the total number of vertices in trg_mesh
    src_point_clouds.features_packed().requires_grad = True

    # The optimizer
    optimizer = torch.optim.SGD([src_point_clouds.features_packed()], lr=1.0, momentum=0.9)

    n_iter = 20000
    epoch = tqdm(range(n_iter))

    loss_f = torch.nn.L1Loss()
    losses = []

    for i in epoch:
        # Initialize optimizer
        optimizer.zero_grad()

        # We compare the two sets of pointclouds by computing the L1 loss
        loss = loss_f(trg_point_clouds.features_packed(), src_point_clouds.features_packed())

        # Print the losses
        epoch.set_description('total_loss = %.6f' % loss)

        # Save the losses for plotting
        losses.append(loss)

        # Optimization step
        loss.backward()
        optimizer.step()
```
it seems that I can get some learning, the loss though decreases extremely slow (it might be though due to the data). Does it seem reasonable to you?

**Comment by SamGalanakis** [comment]
Hey, no idea about the exact problem/ data but maybe play around with the learning rate and try a different optimizer like Adam. Your learning rate is really big so it could just be oscillating around the local optimum, try something smaller like 0.001 or something. Not sure I get what the problem you are trying to solve is though. Is the goal to just estimate pointwise "energy" for a given pointcloud? Cause right now your pointcloud isn't being used in the estimation of your features which is quite odd.

**Comment by ttsesm** [comment]
The problem I am trying to solve is the following. 

Imagine that I have multiple point clouds that are representing different room structures including their objects. For each point I also have the ground truth illuminance (as lux values), that is my features vector, and I also know which of these points correspond to the light sources of the scene (I do not use this information at the moment). So now I want to train my network to learn to estimate this illumination values for a given pointcloud so as you mentioned it is a pointwise "energy" estimation.

In principle my pointcloud information (i.e. geometry) should be taken into account and that's what I am trying to do with the `Pointclouds` class from pytorch3d similarly to what they do with the mesh deformation example. But I cannot really understand how I can do that since the provided examples are limited (for pointclouds there are none actually).

**Comment by SamGalanakis** [comment]
Well pytorch3d just gives efficient ways to do certain rendering / common operations it doesn't have any inbuilt models. You would have to use something like you have above and use a model implemented in pytorch (if you want to use pytorch3d) to make your predictions. If I understand your task correctly it essentially amounts to a segmentation task where you are estimating the light at each point. So you can use something like pointnet++ or [this paper](https://arxiv.org/pdf/1801.07829.pdf) which I happen to be reading now. The only thing different from segmentation would be that you woud be doing regression rather than classification at the end and that you need to somehow include your information about the light sources. Not sure what the most efficient way to do this would be. One way would be to just include an extra feature for each point in the point cloud that represents the intensity of light from that point ( 0 for all but the light sources). So you would have nx4 input and get your pointwise energy as output predictions. There is probably a more efficient way to incorporate the light information though.

**Comment by ttsesm** [comment]
I see, well I quite new to the field so I am trying to understand how pytorch3d can be used, if possible at all. To be honest I am still a bit confused how pytorch3d can be used in comparison to  pytorch, I mean except of providing an efficient method to load 3d point data, e.g. the `Meshes` and `Pointclouds` classes, some specific losses for point cloud matching and the renderer/rasterizer for visualization can be used differently?

Also in your example in this repository, where do you use it? I was checking on the [renderer.py](https://github.com/SamGalanakis/pytorch3dPointnet/blob/main/renderer.py) but I did not find to be used anywhere else.

I was also checking on [torch-point3d](https://github.com/nicolas-chaulet/torch-points3d#methods-currently-implemented) which has already some models included.

Btw, thanks for the link to the paper seems interesting.

**Comment by SamGalanakis** [comment]
Basically pyrorch3d gives highly optimized transformation/metrics/renderers that are differentiable and compatible with pytorch, it isn't standalone. Think of it as an addon for dealing with 3d data, you still need pytorch to implement the actual model. Only really used it for batching and resampling meshes here as well as some visualization, just wanted to try it out wasn't really necessary. Something like the repo you linked would probably be a good choice for you, since implementing one of these models from scratch is quite hard, especially if new to the field. What I would try first is taking one of the segmentation models, giving nx4 input as I described before and just changing the output layer from classification to regression and see how that performs.

**Comment by ttsesm** [comment]
Yup, I will try to go that way and see what I can get. Thanks again for your time and the feedback.

I guess I will close this down for now.
